name: notion-backup
services:
  notion-backup:
    image: ghcr.io/asierzunzu/schedulable-notion-backup:main
    container_name: notion-backup
    volumes:
      - ${BACKUP_PATH}:/${DOWNLOADS_DIRECTORY_PATH}
    env_file: ".env"
    restart: unless-stopped
#    user: "${PUID-1000}:${PGID-1000}"
    labels:
      # Watchtower
      com.centurylinklabs.watchtower.enable: true
