services:
  notion-backup:
    container_name: notion-backup
    image: ghcr.io/asierzunzu/schedulable-notion-backup:main
    env_file: ".env"
    restart: unless-stopped
    volumes:
      - '${BACKUP_PATH}:/downloads'